application: freedomrun-001
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.php)$
  script: \1

# handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|swf|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|swf|xml))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: index.php
