application: freedom-run-666
version: 2
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.php)$
  script: \1

- url: .*
  script: index.php
